server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password: yyh283621917
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false #关闭thymeleaf缓存

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yyh.student.entity
